spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8888
  error:
    include-message: always

security:
  jwt:
    issuer: Sultan
    secret-word: BakirovSultan
    expires-at: 1000
    s-e-c-r-e-t-k-e-y: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
